%YAML 1.1
---
all:
  hosts: {}
modules:
  hosts:
    Mikrotik1: {}
    Mikrotik2: {}
    Mikrotik3: {}
    client1: {}
    client2: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
unprovisioned:
  hosts: {}
  children: {}
netlab_no_reload:
  hosts:
    client1: {}
    client2: {}
routeros7:
  hosts:
    Mikrotik1:
      ansible_host: 192.168.121.101
      id: 1
    Mikrotik2:
      ansible_host: 192.168.121.102
      id: 2
    Mikrotik3:
      ansible_host: 192.168.121.103
      id: 3
netlab_ready_ssh:
  hosts:
    Mikrotik1: {}
    Mikrotik2: {}
    Mikrotik3: {}
linux:
  hosts:
    client1:
      ansible_host: clab-r202OSPF1-client1
      id: 4
    client2:
      ansible_host: clab-r202OSPF1-client2
      id: 5
